spring.application.name=atto
server.port=8080
spring.profiles.active=test

spring.jpa.hibernate.ddl-auto=validate
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.validate-on-migrate=true

# JWT Configuration
jwt.secret-key=YmluYXJpYXNlZ3VyYWRhY29tM2Zlc3RhY2hhdmVzY29tYXRsMjU2Yml0cw==
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000
