spring.datasource.url=jdbc:postgresql://servidor:5432/prod
spring.datasource.username=production
spring.datasource.password=senha_segura
#tenho que ver sobre esse banco aí, colocar um acesso para ele e uma senha potente

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false